--- 
- name: "Git test playbook" 
  hosts: amazon 
  become: true 
  vars_files:
    - variables.yml
  tasks: 
    
    - name: "Installing apache"
      package:
        name: "httpd"
        state: present
         
    - name: "Restart/enable apache"  
      service: 
        name: httpd
        state: restarted
        enabled: true
